target 'HandOff' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Pods for HandOff
pod 'OneSignal'

#target 'HandOffTests' do
#  inherit! :search_paths
# Pods for testing
#end

end
